version: "{build}-{branch}"

branches:
  only:
    - main
    - dev-appveyor

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 25-x64
    - RUBY_VERSION: 26-x64
    # Missing Ruby 2.7 with DevKit?
    # - RUBY_VERSION: 27-x64

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem update --no-document --system 2.7.8
  - gem install bundler --no-document --version="<2.0.0"
  - bundle config --local path vendor/bundle
  - bundle install

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v

test_script:
  - bundle exec rake
